version: "3.7"
name: local
networks:
  cloudtalk:
    driver: bridge
volumes:
  redpanda: null
services:
  mysql:
    container_name: mysql
    image: bitnami/mysql:8.0
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: cloudtalk
    ports:
      - 3306:3306

  redis:
    container_name: redis
    image: bitnami/redis:7.4
    environment:
      REDIS_PASSWORD: pass
    ports:
      - 6379:6379

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.7
    networks:
      - cloudtalk
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094,CONTROLLER://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9094,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - 9092:9092
