name: local
networks:
  cloudtalk:
    driver: bridge
    enable_ipv6: false
services:
  mysql:
    container_name: mysql
    image: bitnami/mysql:8.0
    networks:
      - cloudtalk
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: cloudtalk
    ports:
      - 3306:3306

  redis:
    container_name: redis
    image: bitnami/redis:7.4
    networks:
      - cloudtalk
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 6379:6379

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.7
    networks:
      - cloudtalk
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094,CONTROLLER://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9094,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - 9092:9092

  product_service:
    container_name: product_service
    build: ./product-svc
    networks:
      - cloudtalk
    environment:
      NODE_ENV: development
      PORT: 3000
      KAFKA_BROKERS: kafka:9094
      KAFKA_CLIENT_ID: product-service
      KAFKA_CONSUMER_GROUP_ID: product-service
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASS: pass
      MYSQL_DB: cloudtalk
      REDIS_HOST: redis
    ports:
      - 3000:3000

  review_service:
    build: ./review-svc
    networks:
      - cloudtalk
    deploy:
      mode: replicated
      replicas: 2
    environment:
      NODE_ENV: development
      PORT: 3001
      KAFKA_BROKERS: kafka:9094
      KAFKA_CLIENT_ID: review-service
      KAFKA_CONSUMER_GROUP_ID: review-service
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASS: pass
      MYSQL_DB: cloudtalk